name: reswipe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  change_app_package_name: ^1.4.0
  file_picker: ^8.1.2
  flutter_pdfview: ^1.3.3
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  http: ^1.2.2
  path_provider: ^2.1.4
  flutter_swipable: ^1.2.1
  lottie: ^3.1.2
  flutter_card_swiper:
  shared_preferences:
  google_fonts:
  shimmer:
  flutter_staggered_animations:
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.1
  share_plus: ^10.1.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.0
  flutter_chips_input:
  flutter_email_sender: ^6.0.3
  google_generative_ai: ^0.4.6
  syncfusion_flutter_pdf: ^27.1.57
  firebase_app_check: ^0.3.1+4
  cupertino_icons: ^1.0.8
  firebase_core_web: ^2.18.1
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.14
  google_sign_in_web: ^0.12.4+3
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
     - assets/lottie/
     - assets/google_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
